In [7]:
import pandas as pd

In [8]:
df1=pd.read_csv(r'C:\Users\rvu\Desktop\program\7prog_6Mcd_null_values.csv')

In [9]:
print("\nMissing values in the DataFrame:")
print(df1.isnull().sum())

Missing values in the DataFrame:
Year                          0
McDonalds_Revenue_$Billion    0
Growth_rate_percent           1
Q1                            4
Q2                            4
Q3                            4
Q4                            3
dtype: int64

In [10]:
df1['Q1'].fillna(df1['Q1'].mean(), inplace=True)
print("\nDataFrame after filling missing values in 'Q1' column:")
df1

DataFrame after filling missing values in 'Q1' column:

C:\Users\rvu\AppData\Local\Temp\ipykernel_23532\2192483125.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Q1'].fillna(df1['Q1'].mean(), inplace=True)

    Year  McDonalds_Revenue_$Billion  Growth_rate_percent    Q1   Q2   Q3   Q4
0   1999                        13.3                  NaN  5.43  NaN  NaN  NaN
1   2000                        14.2                  7.0  5.43  NaN  NaN  NaN
2   2001                        14.9                  4.0  5.43  NaN  NaN  NaN
3   2002                        15.4                  4.0  5.43  NaN  NaN  3.0
4   2003                        17.1                 11.0  3.80  4.3  4.5  4.6
5   2004                        18.6                  8.0  4.40  4.7  4.9  4.5
6   2005                        19.1                  3.0  4.80  5.1  5.3  3.9
7   2006                        20.9                  9.0  4.90  5.4  5.5  5.1
8   2007                        22.8                  9.0  5.30  5.8  5.9  5.8
9   2008                        23.5                  3.0  5.60  6.1  6.3  5.6
10  2009                        22.7                 -3.0  5.10  5.6  6.0  6.0
11  2010                        24.1                  6.0  5.60  5.9  6.3  6.2
12  2011                        27.0                 12.0  6.10  6.9  7.2  6.8
13  2012                        27.6                  2.0  6.50  6.9  7.2  7.0
14  2013                        28.1                  2.0  6.60  7.1  7.3  7.1
15  2014                        27.4                 -2.0  6.70  7.2  7.0  6.6
16  2015                        25.4                 -7.0  6.00  6.5  6.6  6.3
17  2016                        24.6                 -3.0  5.90  6.3  6.4  6.0
18  2017                        22.8                 -7.0  5.70  6.0  5.8  5.3
19  2018                        21.3                 -7.0  5.10  5.4  5.4  5.4
20  2019                        21.4                  1.0  5.00  5.3  5.6  5.4
21  2020                        19.2                -10.0  4.70  3.8  5.4  5.3
22  2021                        23.2                 21.0  5.10  5.9  6.2  6.0
23  2022                        23.2                  0.0  5.70  5.7  5.9  5.9

In [11]:
print("\nMissing values in the DataFrame:")
print(df1.isnull().sum())

Missing values in the DataFrame:
Year                          0
McDonalds_Revenue_$Billion    0
Growth_rate_percent           1
Q1                            0
Q2                            4
Q3                            4
Q4                            3
dtype: int64

In [12]:
df1['Q2'].fillna(df1['Q2'].mean(), inplace=True)
print("\nDataFrame after filling missing values in 'Q2' column:")
df1

DataFrame after filling missing values in 'Q2' column:

C:\Users\rvu\AppData\Local\Temp\ipykernel_23532\2924243464.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Q2'].fillna(df1['Q2'].mean(), inplace=True)

,Year,McDonalds_Revenue_$Billion,Growth_rate_percent,Q1,Q2,Q3,Q4
0,1999,13.3,NaN,5.43,5.795,NaN,NaN
1,2000,14.2,7.0,5.43,5.795,NaN,NaN
2,2001,14.9,4.0,5.43,5.795,NaN,NaN
3,2002,15.4,4.0,5.43,5.795,NaN,3.0
4,2003,17.1,11.0,3.80,4.300,4.5,4.6
5,2004,18.6,8.0,4.40,4.700,4.9,4.5
6,2005,19.1,3.0,4.80,5.100,5.3,3.9
7,2006,20.9,9.0,4.90,5.400,5.5,5.1
8,2007,22.8,9.0,5.30,5.800,5.9,5.8
9,2008,23.5,3.0,5.60,6.100,6.3,5.6
10,2009,22.7,-3.0,5.10,5.600,6.0,6.0
11,2010,24.1,6.0,5.60,5.900,6.3,6.2
12,2011,27.0,12.0,6.10,6.900,7.2,6.8
13,2012,27.6,2.0,6.50,6.900,7.2,7.0
14,2013,28.1,2.0,6.60,7.100,7.3,7.1
15,2014,27.4,-2.0,6.70,7.200,7.0,6.6
16,2015,25.4,-7.0,6.00,6.500,6.6,6.3
17,2016,24.6,-3.0,5.90,6.300,6.4,6.0
18,2017,22.8,-7.0,5.70,6.000,5.8,5.3
19,2018,21.3,-7.0,5.10,5.400,5.4,5.4
20,2019,21.4,1.0,5.00,5.300,5.6,5.4
21,2020,19.2,-10.0,4.70,3.800,5.4,5.3
22,2021,23.2,21.0,5.10,5.900,6.2,6.0
23,2022,23.2,0.0,5.70,5.700,5.9,5.9

In [13]:
print("\nMissing values in the DataFrame:")
print(df1.isnull().sum())

Missing values in the DataFrame:
Year                          0
McDonalds_Revenue_$Billion    0
Growth_rate_percent           1
Q1                            0
Q2                            0
Q3                            4
Q4                            3
dtype: int64

In [14]:
df1['Q3'].fillna(df1['Q3'].mean(), inplace=True)
print("\nDataFrame after filling missing values in 'Q3' column:")
df1

DataFrame after filling missing values in 'Q3' column:

C:\Users\rvu\AppData\Local\Temp\ipykernel_23532\1076317282.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Q3'].fillna(df1['Q3'].mean(), inplace=True)

,Year,McDonalds_Revenue_$Billion,Growth_rate_percent,Q1,Q2,Q3,Q4
0,1999,13.3,NaN,5.43,5.795,6.035,NaN
1,2000,14.2,7.0,5.43,5.795,6.035,NaN
2,2001,14.9,4.0,5.43,5.795,6.035,NaN
3,2002,15.4,4.0,5.43,5.795,6.035,3.0
4,2003,17.1,11.0,3.80,4.300,4.500,4.6
5,2004,18.6,8.0,4.40,4.700,4.900,4.5
6,2005,19.1,3.0,4.80,5.100,5.300,3.9
7,2006,20.9,9.0,4.90,5.400,5.500,5.1
8,2007,22.8,9.0,5.30,5.800,5.900,5.8
9,2008,23.5,3.0,5.60,6.100,6.300,5.6
10,2009,22.7,-3.0,5.10,5.600,6.000,6.0
11,2010,24.1,6.0,5.60,5.900,6.300,6.2
12,2011,27.0,12.0,6.10,6.900,7.200,6.8
13,2012,27.6,2.0,6.50,6.900,7.200,7.0
14,2013,28.1,2.0,6.60,7.100,7.300,7.1
15,2014,27.4,-2.0,6.70,7.200,7.000,6.6
16,2015,25.4,-7.0,6.00,6.500,6.600,6.3
17,2016,24.6,-3.0,5.90,6.300,6.400,6.0
18,2017,22.8,-7.0,5.70,6.000,5.800,5.3
19,2018,21.3,-7.0,5.10,5.400,5.400,5.4
20,2019,21.4,1.0,5.00,5.300,5.600,5.4
21,2020,19.2,-10.0,4.70,3.800,5.400,5.3
22,2021,23.2,21.0,5.10,5.900,6.200,6.0
23,2022,23.2,0.0,5.70,5.700,5.900,5.9

In [15]:
print("\nMissing values in the DataFrame:")
print(df1.isnull().sum())

Missing values in the DataFrame:
Year                          0
McDonalds_Revenue_$Billion    0
Growth_rate_percent           1
Q1                            0
Q2                            0
Q3                            0
Q4                            3
dtype: int64

In [16]:
df1['Q4'].fillna(df1['Q4'].mean(), inplace=True)
print("\nDataFrame after filling missing values in 'Q4' column:")
df1

DataFrame after filling missing values in 'Q4' column:

C:\Users\rvu\AppData\Local\Temp\ipykernel_23532\2697065869.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Q4'].fillna(df1['Q4'].mean(), inplace=True)

,Year,McDonalds_Revenue_$Billion,Growth_rate_percent,Q1,Q2,Q3,Q4
0,1999,13.3,NaN,5.43,5.795,6.035,5.609524
1,2000,14.2,7.0,5.43,5.795,6.035,5.609524
2,2001,14.9,4.0,5.43,5.795,6.035,5.609524
3,2002,15.4,4.0,5.43,5.795,6.035,3.000000
4,2003,17.1,11.0,3.80,4.300,4.500,4.600000
5,2004,18.6,8.0,4.40,4.700,4.900,4.500000
6,2005,19.1,3.0,4.80,5.100,5.300,3.900000
7,2006,20.9,9.0,4.90,5.400,5.500,5.100000
8,2007,22.8,9.0,5.30,5.800,5.900,5.800000
9,2008,23.5,3.0,5.60,6.100,6.300,5.600000
10,2009,22.7,-3.0,5.10,5.600,6.000,6.000000
11,2010,24.1,6.0,5.60,5.900,6.300,6.200000
12,2011,27.0,12.0,6.10,6.900,7.200,6.800000
13,2012,27.6,2.0,6.50,6.900,7.200,7.000000
14,2013,28.1,2.0,6.60,7.100,7.300,7.100000
15,2014,27.4,-2.0,6.70,7.200,7.000,6.600000
16,2015,25.4,-7.0,6.00,6.500,6.600,6.300000
17,2016,24.6,-3.0,5.90,6.300,6.400,6.000000
18,2017,22.8,-7.0,5.70,6.000,5.800,5.300000
19,2018,21.3,-7.0,5.10,5.400,5.400,5.400000
20,2019,21.4,1.0,5.00,5.300,5.600,5.400000
21,2020,19.2,-10.0,4.70,3.800,5.400,5.300000
22,2021,23.2,21.0,5.10,5.900,6.200,6.000000
23,2022,23.2,0.0,5.70,5.700,5.900,5.900000