In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("5prog_1experience.csv")

In [3]:
df

   YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2
5              2.9
6              3.0
7              3.2
8              3.2

In [4]:
df.shape

(9, 1)

In [5]:
len(df)

9

In [6]:
df.head(3)

   YearsExperience
0              1.1
1              1.3
2              1.5

In [1]:
try:
  a=b
except:
  print("The variable has not been assigned")

The variable has not been assigned

In [2]:
try:
  a=b
except NameError as ex:
  print(ex)

name 'b' is not defined

In [3]:
try:
    result=1/0
except ZeroDivisionError as ex:
    print(ex)
    print("Please enter the denominator grater than 0")

division by zero
Please enter the denominator grater than 0

In [ ]:
#try:risky errors are typed here
#except:error handling
#else:when there are no error in the code else will be executed
#finally:conclusion type no matter if errors are there or not finally will be executed
#exeption means general error, it will handel all the error if it is not mentioned
#while printing it will take only first error, and ignores the second error

In [7]:
try:
    result=1/2
    a=b
except ZeroDivisionError as ex:
    print(ex)
    print("Please enter the denominator grater than 0")    
except Exception as ex1:
    print(ex1)
    print("Main exeption caught here")

name 'b' is not defined
Main exeption caught here

In [8]:
try:
    result=1/0
    a=b
except ZeroDivisionError as ex:
    print(ex)
    print("Please enter the denominator grater than 0")    
except Exception as ex1:
    print(ex1)
    print("Main exeption caught here")

division by zero
Please enter the denominator grater than 0